Repository codestates-seb/seb41_main_028, pull requests merged in 2023-02, with the labels that each got.

#355 feat - #345: 웹 푸시 관련 수정 중
  client/components/pushSubscribe.tsx
  client/pages/api/webpush.ts
  client/util/firebase.ts
Labels: FE, Feat

#353 feat: 더미데이터 추가, 통계 로우 데이터 전달
  server/src/main/java/challenge/server/file/storage/AmazonS3ResourceStorage.java
  server/src/main/java/challenge/server/habit/entity/AgeRatio.java
  server/src/main/java/challenge/server/habit/entity/SexRatio.java
  server/src/main/java/challenge/server/habit/entity/StatusRatio.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, Feat

#356 feat - #345: 웹 푸시 관련 수정 중
  client/pages/api/webpush.ts
  client/public/firebase-messaging-sw.js
  client/util/firebase.ts
Labels: FE, Feat

#357 feat - #345: 웹 푸시 관련 수정 중
  client/pages/api/webpush.ts
  client/pages/oauth.tsx
Labels: FE, Feat

#358 feat: 습관 body length 수정
  server/src/main/java/challenge/server/habit/entity/Habit.java
Labels: BE, Feat

#359 feat: habit body 타입 @lob 설정
  server/src/main/java/challenge/server/habit/entity/Habit.java
Labels: BE, Feat

#360 fix - #352: 각종 버그 수정
  client/components/header.tsx
  client/components/pushSubscribe.tsx
  client/module/moduleInterface.ts
  client/module/userFunctionMoudules.ts
  client/pages/user/mypage/index.tsx
  client/pages/user/signup.tsx
Labels: FE, Fix

#361 feat - #345: 웹 푸시 관련 수정 중
  client/components/bottomNav/editHabitBottomNav.tsx
  client/components/pushSubscribe.tsx
  client/ducks/loginIdentitySlice.ts
  client/pages/api/webpushcancel.ts
  client/pages/habit/post.tsx
Labels: FE, Feat

#362 fix - #352: 디버깅
  client/pages/auth/index.tsx
  client/pages/user/mypage/index.tsx
Labels: FE, Fix

#364 design - #363: Habit Detail UI 수정
  client/components/header.tsx
  client/pages/habit/detail/[habitId]/index.tsx
Labels: FE, Design

#365 feat: challenge 응답데이터 subtitle 추가
  server/src/main/java/challenge/server/challenge/dto/ChallengeDto.java
  server/src/main/java/challenge/server/challenge/mapper/ChallengeMapper.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/db/h2/data.sql
Labels: BE, Feat

#370 feat - #345: 카테고리 맵핑, 알림기능 팝업 창 구현, 후기 중복 등록 금지
  client/components/bottomNav/reviewHabitBottomNav.tsx
  client/components/pushSubscribe.tsx
  client/module/reviewFunctionModules.ts
  client/pages/habit/search/index.tsx
Labels: FE, Feat, Design

#372 feat - #345: 푸시 알림 관련
  client/components/pushSubscribe.tsx
  client/pages/api/autopush.ts
  client/pages/api/hello.js
  client/pages/api/webpush.ts
  client/pages/api/webpushcancel.ts
  client/public/firebase-messaging-sw.js
Labels: FE, Feat

#375 feat: Challenge 재시작 시 createdAt 초기화
  server/src/main/java/challenge/server/audit/BaseTimeEntity.java
  server/src/main/java/challenge/server/challenge/entity/Challenge.java
Labels: BE, Feat

#377 feat: 톰캣 서버 시간 변경(Asia/Seoul)
  server/src/main/java/challenge/server/ServerApplication.java
Labels: BE, Feat

#380 feat - #366: 습관 시작 시 Detail Page UI 및 기능 수정
  client/ducks/loginIdentitySlice.ts
  client/module/authFunctionMoudules.ts
  client/module/bookmarkFunctionMoudules.ts
  client/module/challengeFunctionMoudules.ts
  client/module/habitFunctionMoudules.ts
  client/module/reportFunctionMoudules.ts
  client/module/reviewFunctionModules.ts
  client/module/userFunctionMoudules.ts
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/oauth.tsx
Labels: FE, Feat

#381 fix - 컴파일 오류 수정
  server/src/main/java/challenge/server/user/service/UserService.java
Labels: BE, Fix

#383 docs: habit 썸네일 이미지 추가
  server/src/main/resources/db/h2/data.sql
Labels: BE, Docs

#384 feat - #352: 디버깅, 마이페이지 통계 추가 1차
  client/components/myPageMenuList.tsx
  client/module/moduleInterface.ts
  client/module/userFunctionMoudules.ts
  client/pages/auth/index.tsx
  client/pages/user/mypage/index.tsx
  client/tailwind.config.js
Labels: FE, Feat, Fix, Design

#385 docs: user 프로필 이미지 url 수정
  server/src/main/resources/db/h2/data.sql
Labels: BE, Docs

#386 design - #366: MyPage, Habit Detail 전반적인 UI 수정 및 에러 해결
  client/components/bottomNav/editHabitBottomNav.tsx
  client/components/bottomNav/mainBottomNav.tsx
  client/components/bottomNav/reviewHabitBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
  client/components/dropDown.tsx
  client/components/habitElement.tsx
  client/components/header.tsx
  client/components/layout/layout.tsx
  client/components/myPageMenuList.tsx
  client/components/pushSubscribe.tsx
  client/module/reportFunctionMoudules.ts
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/habit/edit/[habitId].tsx
  client/pages/user/mypage/index.tsx
  client/public/image/baseProfile.svg
Labels: FE, Fix, Design

#388 fix - #352: 마이페이지 디버그
  client/pages/user/mypage/index.tsx
Labels: FE, Fix

#392 fix - #25 #28: 마이페이지 조회 버그 수정, 주석 추가
  server/src/main/java/challenge/server/bookmark/repository/BookmarkRepository.java
  server/src/main/java/challenge/server/config/SecurityConfig.java
  server/src/main/java/challenge/server/security/handler/UserAccessDeniedHandler.java
  server/src/main/java/challenge/server/security/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/challenge/server/security/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/challenge/server/security/handler/UserAuthenticationSuccessHandler.java
  server/src/main/java/challenge/server/security/jwt/JwtTokenizer.java
  server/src/main/java/challenge/server/security/utils/CustomAuthorityUtils.java
  server/src/main/java/challenge/server/user/service/UserService.java
Labels: BE, Fix, Comment

#394 fix - #366: Search Page 에러 수정 및 일부 UI 수정
  client/components/habitWrapperVertical.tsx
  client/components/slideBanner.tsx
  client/pages/auth/index.tsx
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/habit/search/index.tsx
Labels: FE, Fix, Design

#395 feat - #345: 리뷰 수정 관련 구현
  client/.gitignore
  client/components/bottomNav/reviewHabitBottomNav.tsx
  client/components/dropDown.tsx
  client/components/reviewArticle.tsx
  client/module/reviewFunctionModules.ts
  client/pages/index.tsx
Labels: FE, Feat

#396 feat - #345: 리뷰 수정 관련 구현
  client/components/dropDown.tsx
Labels: FE, Feat

#397 eat - #345: 인증 수정 기능 추가
  client/components/authArticle.tsx
  client/components/bottomNav/mainBottomNav.tsx
  client/components/bottomNav/reviewHabitBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
  client/components/dropDown.tsx
  client/components/modal.tsx
  client/module/authFunctionMoudules.ts
  client/module/challengeFunctionMoudules.ts
  client/pages/auth/index.tsx
  client/pages/habit/detail/[habitId]/auth.tsx
Labels: FE, Feat

#398 feat: ddl-auto validate 설정
  server/build.gradle
  server/src/main/java/challenge/server/commons/firebase/FCMService.java
  server/src/main/java/challenge/server/commons/firebase/FCMTokenDao.java
  server/src/main/java/challenge/server/commons/firebase/FCMinitializer.java
  server/src/main/java/challenge/server/user/entity/User.java
  server/src/main/java/challenge/server/user/service/UserService.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/challenge-375405-firebase-adminsdk-ymetp-3cc2c2692f.json
Labels: BE, Docs

#400 refactor - #366: Habit Edit Page getServerSideProps로 Refactoring
  client/module/moduleInterface.ts
  client/pages/habit/edit/[habitId].tsx
Labels: FE, Refactor

#401 feat - #352: 마이페이지 통계 구현
  client/package-lock.json
  client/package.json
  client/pages/user/mypage/index.tsx
Labels: FE, Feat, Design

#402 style - #366: Infinite Scroll 오타 수정
  client/hooks/useIntersection.ts
Labels: FE, Style

#403 feat: Habit 상세 DTO allChallengers 필드 추가
  server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepository.java
  server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepositoryImpl.java
  server/src/main/java/challenge/server/habit/dto/HabitDto.java
  server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
Labels: BE, Feat

#406 design - #382: Auth Page Base Height 조정
  client/pages/auth/index.tsx
Labels: FE, Design

#407 fix: 이미지 저장 로직 수정
  server/src/main/java/challenge/server/habit/controller/HabitController.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, Fix

#413 feat: 마이페이지 통계 모바일 환경 UI 변경, 인증서 발급시 카카오톡 연계
  client/components/myPageMenuList.tsx
  client/pages/user/mypage/index.tsx
Labels: FE, Feat

#414 feat - #345: 하단 네비게이션 조건에 따른 텍스트 수정
  client/components/bottomNav/editHabitBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
Labels: FE, Feat

#416 fix: 습관 통계 LazyInitializationException 해결
  server/src/main/java/challenge/server/habit/controller/HabitController.java
  server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
  server/src/main/java/challenge/server/habit/service/HabitService.java
  server/src/main/java/challenge/server/user/entity/User.java
Labels: BE, Fix

#417 fix: 인증글 등록 시 LazyException 수정
  server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
  server/src/main/java/challenge/server/challenge/service/ChallengeService.java
Labels: BE, Fix

#419 feat - #412: 마이페이지 데이터 변경, 콘솔제거, 인증서 공유 url 변경
  client/components/myPageMenuList.tsx
  client/pages/user/mypage/index.tsx
Labels: FE, Feat

#420 feat: LazyInitializationException 해결
  server/src/main/java/challenge/server/habit/controller/HabitController.java
  server/src/main/java/challenge/server/habit/entity/AgeRatio.java
  server/src/main/java/challenge/server/habit/service/HabitService.java
Labels: BE, Fix

#425 fix - 더미데이터(Challenge 날짜) 수정
  server/src/main/resources/db/h2/data.sql
Labels: BE, Fix

#427 feat - #412: Oauth 리다이렉트, 메인 문구 일부 수정, 통계 일부 수정
  client/module/moduleInterface.ts
  client/pages/index.tsx
  client/pages/user/mypage/index.tsx
  client/pages/user/oauthsignup.tsx
Labels: FE, Feat, Fix

#428 feat: age, gender 필드 추가
  server/src/main/java/challenge/server/user/dto/UserDto.java
  server/src/main/java/challenge/server/user/service/UserService.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, Feat, Docs

#430 fix - #429: OAuth 리다이렉트 이슈 해결
  client/components/header.tsx
  client/module/userFunctionMoudules.ts
  client/pages/user/oauthsignup.tsx
Labels: FE, Fix

#433 fix - #429: OAuth 리다이렉트 이슈 해결, 콘솔제거
  client/pages/user/oauthsignup.tsx
Labels: FE, Fix

#437 feat - #434: 두번째 슬라이드 누를때 카톡링크 공유
  client/pages/user/mypage/tomobile.tsx
Labels: FE, Feat

#438 design - #382: z-index 조정
  client/components/bottomNav/startHabitBottomNav.tsx
  client/components/slideBanner.tsx
  client/pages/user/guest.tsx
  client/tailwind.config.js
Labels: Feat, Design

#439 feat - #345: 하단 네비게이션 수정
  client/components/bottomNav/editHabitBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
Labels: FE, Feat

#441 design - #382: Habit Detail UI 수정
  client/pages/habit/detail/[habitId]/auth.tsx
  client/pages/habit/detail/[habitId]/review.tsx
Labels: FE, Design

#443 fix: LazyInitializationException 해결, 더미데이터 추가
  server/src/main/java/challenge/server/habit/controller/HabitController.java
  server/src/main/java/challenge/server/review/service/ReviewService.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, Docs

#446 docs: 더미데이터 추가
  server/src/main/resources/db/h2/data.sql
Labels: BE, Docs

#449 fix - #382: Habit Detail 내 오류 수정
  client/components/alert.tsx
  client/components/dropDown.tsx
  client/components/layout/layout.tsx
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/user/login.tsx
Labels: FE, Fix

#459 feat: 알림 route 기능 구현
  server/src/main/java/challenge/server/firebase/FCMService.java
  server/src/main/java/challenge/server/review/service/ReviewService.java
  server/src/main/java/challenge/server/user/controller/UserController.java
  server/src/main/java/challenge/server/user/service/UserService.java
Labels: BE, Feat

#464 feat: FCM 푸쉬 알림 Title 수정
  server/src/main/java/challenge/server/firebase/FCMService.java
  server/src/main/java/challenge/server/review/service/ReviewService.java
Labels: BE, Feat

#467 feat - #465: websocket 외부 라이브러리 의존 추가
  server/build.gradle
Labels: BE, Feat

#468 fix: SecurityConfig CORS 설정 수정
  server/src/main/java/challenge/server/config/SecurityConfig.java
Labels: BE, Fix

#469 fix: SecurityConfig, WebMvcConfig CORS 설정 수정
  server/src/main/java/challenge/server/config/SecurityConfig.java
  server/src/main/java/challenge/server/config/WebMvcConfig.java
Labels: BE
