Repository codestates-seb/seb41_main_028, pull requests merged in 2023-01, with the labels that each got.

#48 feat - #10: Add deploy.sh, appspec.yml
  server/appspec.yml
  server/scripts/deploy.sh
Labels: BE, Feat

#51 feat - #19: API 통신을 위한 기본 Dto, Controller 구현(Challenge, Review, Auth)
  server/src/main/java/challenge/server/auth/controller/AuthController.java
  server/src/main/java/challenge/server/auth/dto/AuthDto.java
  server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
  server/src/main/java/challenge/server/challenge/dto/ChallengeDto.java
  server/src/main/java/challenge/server/review/controller/ReviewController.java
  server/src/main/java/challenge/server/review/dto/ReviewDto.java
Labels: BE, Feat

#53 feat - #10: Add gradle.yml for Github Actions
  server/.github/workflows/gradle.yml
Labels: BE, Feat

#54 fix - #10: gradle.yml 빌드 경로 수정
  .github/workflows/gradle.yml
Labels: BE, Fix, Rename

#58 fix - #10: application.yml 프로필 지정
  server/scripts/deploy.sh
Labels: BE, Fix

#63 fix - #62: 리베이스 머지 충돌 확인
  client/pages/user/login.js
  client/pages/user/signUp.js
  client/tailwind.config.js
Labels: Fix

#68 docs: Update .gitignore
  .gitignore
Labels: BE, Docs

#70 fix - #11: 비밀번호 제약 조건 수정
  server/.gradle/7.6/fileHashes/fileHashes.lock
  server/.gradle/buildOutputCleanup/outputFiles.bin
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/src/main/java/challenge/server/user/controller/UserController.java
  server/src/main/java/challenge/server/user/entity/User.java
Labels: BE, Fix

#71 fix - #11: 서비스 transcational 애너테이션 수정
  server/src/main/java/challenge/server/user/service/UserService.java
Labels: BE, Fix

#72 feat - #64: Home Page UI 구현
  client/.gitignore
  client/components/fileUploader.js
  client/components/habitWrapperHorizontal.js
  client/components/habitWrapperVertical.js
  client/components/homeNav.js
  client/components/slideBanner.js
  client/data/homeStaticData.js
  client/pages/_app.js
  client/pages/home/hotlist.js
  client/pages/home/newlist.js
  client/pages/home/recommendlist.js
  client/pages/index.js
  client/pages/user/login.js
  client/tailwind.config.js
Labels: FE, Feat

#73 feat - #67: Edit Userinfo Page UI 구현, Auth Page UI 구현
  client/components/bottomNav/bottomNav.js
  client/components/bottomNav/editHabitBottomNav.js
  client/components/bottomNav/mainBottomNav.js
  client/components/bottomNav/reviewHabitBottomNav.js
  client/components/bottomNav/startHabitBottomNav.js
  client/components/fileUploader.js
  client/pages/auth/index.js
  client/pages/user/mypage/edit.js
  client/pages/user/signUp.js
  client/tailwind.config.js
Labels: FE, Feat, Design

#74 feat - #65: Habit Post UI 구현 1차
  client/.env
  client/components/fileUploader.js
  client/pages/_app.js
  client/pages/auth/index.js
  client/pages/habit/post.js
  client/pages/index.js
  client/pages/user/mypage/edit.js
  client/pages/user/signUp.js
  client/public/image/icons/exercise.svg
Labels: FE, Feat, Fix

#77 fix - #11: 로그인 응답 데이터 수정
  server/.gradle/7.6/fileHashes/fileHashes.lock
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/src/main/java/challenge/server/config/SecurityConfig.java
  server/src/main/java/challenge/server/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/challenge/server/user/controller/UserController.java
  server/src/main/java/challenge/server/user/dto/UserDto.java
  server/src/main/java/challenge/server/user/entity/User.java
  server/src/main/java/challenge/server/user/entity/UserStatus.java
  server/src/main/java/challenge/server/validator/Password.java
  server/src/main/java/challenge/server/validator/PasswordValidator.java
Labels: BE, Fix

#80 feat - #65: Habit Post Page UI 구현
  client/components/fileUploader.js
  client/components/habitWrapperHorizontal.js
  client/components/habitWrapperVertical.js
  client/data/homeStaticData.js
  client/package-lock.json
  client/package.json
  client/pages/habit/post.js
  client/pages/index.js
  client/pages/user/login.js
Labels: FE, Feat, Fix, Refactor

#85 feat - #81: RTK를 활용하여 전역 상태 관리 로직 구현
  client/components/bottomNav/mainBottomNav.js
  client/ducks/loginIdentitySlice.js
  client/ducks/store.js
  client/pages/_app.js
  client/pages/user/login.js
Labels: FE, Feat

#83 feat - #7: Header 컴포넌트 구현
  client/components/header.js
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.js
  client/public/SvgjsG2027 66x58.svg
Labels: FE, Feat, Design, Comment

#87 feat - #86: PWA 기본 환경 세팅
  client/components/header.js
  client/ducks/loginIdentitySlice.js
  client/ducks/store.js
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/_app.js
  client/pages/_document.js
  client/pages/habit/edit/[habitId].js
  client/pages/habit/search/index.js
  client/pages/user/login.js
  client/pages/user/mypage/index.js
  client/pages/user/mypage/madeHabit.js
  client/pages/user/mypage/savedHabit.js
  client/public/image/favicons/android-icon-144x144.png
  client/public/image/favicons/android-icon-192x192.png
  client/public/image/favicons/android-icon-36x36.png
  client/public/image/favicons/android-icon-48x48.png
  client/public/image/favicons/android-icon-72x72.png
  client/public/image/favicons/android-icon-96x96.png
  client/public/image/favicons/apple-icon-114x114.png
  client/public/image/favicons/apple-icon-120x120.png
  client/public/image/favicons/apple-icon-144x144.png
  client/public/image/favicons/apple-icon-152x152.png
  client/public/image/favicons/apple-icon-180x180.png
  client/public/image/favicons/apple-icon-57x57.png
  client/public/image/favicons/apple-icon-60x60.png
  client/public/image/favicons/apple-icon-72x72.png
  client/public/image/favicons/apple-icon-76x76.png
  client/public/image/favicons/apple-icon-precomposed.png
  client/public/image/favicons/apple-icon.png
  client/public/image/favicons/browserconfig.xml
  client/public/image/favicons/favicon-16x16.png
  client/public/image/favicons/favicon-32x32.png
  client/public/image/favicons/favicon-96x96.png
  client/public/image/favicons/ms-icon-144x144.png
  client/public/image/favicons/ms-icon-150x150.png
  client/public/image/favicons/ms-icon-310x310.png
  client/public/image/favicons/ms-icon-70x70.png
  client/public/image/icons/icon-192x192.png
  client/public/image/icons/icon-256x256.png
  client/public/image/icons/icon-384x384.png
  client/public/image/icons/icon-512x512.png
  client/public/manifest.json
  client/public/sw.js
  client/public/sw.js.map
  client/public/workbox-327c579b.js
  client/public/workbox-327c579b.js.map
Labels: FE, Feat

#90 rename: 캐시 초기화
  server/.gradle/7.6/fileHashes/fileHashes.lock
  server/.gradle/buildOutputCleanup/outputFiles.bin
  server/HELP.md
  server/build/bootJarMainClassName
  server/build/generated/querydsl/challenge/server/audit/QBaseTimeEntity.java
  server/build/generated/querydsl/challenge/server/auth/entity/QAuth.java
  server/build/generated/querydsl/challenge/server/bookmark/entity/QBookmark.java
  server/build/generated/querydsl/challenge/server/challenge/entity/QChallenge.java
  server/build/generated/querydsl/challenge/server/challenge/entity/QChallengeStatus.java
  server/build/generated/querydsl/challenge/server/challenge/entity/QWildcard.java
  server/build/generated/querydsl/challenge/server/habit/entity/QCategory.java
  server/build/generated/querydsl/challenge/server/habit/entity/QHabit.java
  server/build/generated/querydsl/challenge/server/report/entity/QReport.java
  server/build/generated/querydsl/challenge/server/review/entity/QReview.java
  server/build/generated/querydsl/challenge/server/user/entity/QUser.java
  server/build/generated/querydsl/challenge/server/user/entity/QUserStatus.java
  server/build/reports/tests/test/classes/challenge.server.ServerApplicationTests.html
  server/build/reports/tests/test/classes/challenge.server.config.JasyptConfigTest.html
  server/build/reports/tests/test/css/base-style.css
  server/build/reports/tests/test/css/style.css
  server/build/reports/tests/test/index.html
  server/build/reports/tests/test/js/report.js
  server/build/reports/tests/test/packages/challenge.server.config.html
  server/build/reports/tests/test/packages/challenge.server.html
  server/build/resources/main/application-local.yml
  server/build/resources/main/application-server.yml
  server/build/resources/test/application.yml
  server/build/test-results/test/TEST-challenge.server.ServerApplicationTests.xml
  server/build/test-results/test/TEST-challenge.server.config.JasyptConfigTest.xml
  server/build/test-results/test/binary/output.bin
  server/build/test-results/test/binary/output.bin.idx
  server/build/test-results/test/binary/results.bin
  server/build/tmp/bootJar/MANIFEST.MF
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/build/tmp/compileTestJava/previous-compilation-data.bin
  server/build/tmp/jar/MANIFEST.MF
  server/out/production/resources/application-local.yml
  server/out/production/resources/application-server.yml
  server/out/test/resources/application.yml
  server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
  server/src/main/java/challenge/server/challenge/dto/ChallengeDto.java
  server/src/main/java/challenge/server/challenge/entity/Challenge.java
  server/src/main/java/challenge/server/challenge/entity/ChallengeStatus.java
  server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepository.java
  server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepositoryImpl.java
  server/src/main/java/challenge/server/challenge/repository/ChallengeRepository.java
  server/src/main/java/challenge/server/challenge/repository/ChallengeStatusRepository.java
  server/src/main/java/challenge/server/challenge/service/ChallengeService.java
  server/src/main/java/challenge/server/review/entity/Review.java
  server/src/test/java/challenge/server/challenge/repository/ChallnegeRepositoryTest.java
Labels: BE, Rename, Remove

#94 feat - #88: 내가 만든 습관 페이지 구현
  client/package-lock.json
  client/package.json
  client/pages/user/mypage/madeHabit.js
  client/pages/user/mypage/madehabit.js
  client/public/sw.js.map
Labels: FE, Feat

#95 feat - #92: Infinite Scroll 구현 (custom hook)
  client/components/habitWrapperVertical.js
  client/components/header.js
  client/components/homeNav.js
  client/components/loadingIndicator.js
  client/hooks/useIntersection.js
  client/package-lock.json
  client/package.json
  client/pages/home/hotlist.js
  client/public/sw.js.map
Labels: FE, Feat

#98 feat - #7: Header 컴포넌트 최종수정
  client/components/header.js
  client/public/image/66logo.png
  client/public/sw.js.map
  client/tailwind.config.js
Labels: FE, Design, Style

#100 feat - #97 Habit Search Page UI 구현
  client/pages/habit/search/index.js
Labels: FE, Feat

#102 feat - #97: 바텀 내비게이션 수정 및 검색 페이지 UI 구현
  client/components/bottomNav/bottomNav.js
  client/components/bottomNav/mainBottomNav.js
  client/hooks/useIntersection.js
  client/package-lock.json
  client/package.json
  client/pages/_app.js
  client/pages/_document.js
  client/pages/habit/search/index.js
  client/pages/user/mypage/madehabit.js
Labels: FE, Feat

#104 fix: build를 위해 test 코드 주석 처리
  server/src/test/java/challenge/server/challenge/repository/ChallnegeRepositoryTest.java
  server/src/test/java/challenge/server/challenge/repository/WildcardRepositoryTest.java
Labels: BE, Fix

#110 fix - #28: 작성 중인 UserRepositoryTest 주석 처리
  server/src/test/java/challenge/server/user/repository/UserRepositoryTest.java
Labels: BE, Fix

#112 feat - #66: Habit Detail UI 구현 2차, Next/Layout 도입 외 코드 수정 다수
  client/components/authArticle.js
  client/components/checkButton.js
  client/components/dropDown.js
  client/components/habitElement.js
  client/components/header.js
  client/components/homeNav.js
  client/components/layout/layout.js
  client/components/reviewArticle.js
  client/components/skyPinkButton.js
  client/components/topNav.js
  client/data/homeStaticData.js
  client/data/navData.js
  client/next.config.js
  client/pages/_app.js
  client/pages/habit/detail/[habitId]/auth.js
  client/pages/habit/detail/[habitId]/index.js
  client/pages/habit/detail/[habitId]/review.js
  client/pages/habit/detail/[habitId]/statistic.js
  client/pages/habit/search/index.js
  client/pages/index.js
  client/public/image/icons/eco.png
  client/public/image/icons/etc.png
  client/public/image/icons/exercise.png
  client/public/image/icons/exercise.svg
  client/public/image/icons/food.png
  client/public/image/icons/hobby.png
  client/public/image/icons/life.png
  client/public/image/icons/selfcare.png
  client/public/image/icons/study.png
  client/public/sw.js.map
  client/styles/globals.css
Labels: FE, Feat, Fix, Design, Refactor, Comment

#113 feat - #103: 현재 api 명세 기반 비동기 함수 작성 및 top scroll 버튼 작성
  client/components/layout/layout.js
  client/components/scrollToTopButton.js
  client/module/authFunctionMoudules.js
  client/module/bookmarkFunctionMoudules.js
  client/module/categoryFunctionMoudules.js
  client/module/challengeFunctionMoudules.js
  client/module/habitFunctionMoudules.js
  client/module/reportFunctionMoudules.js
  client/module/reviewFunctionModules.js
  client/module/userFunctionMoudules.js
  client/pages/habit/search/index.js
  client/public/sw.js.map
Labels: FE, Feat

#115 fix - #66: Habit Detail 포함 일부 코드 수정
  client/components/scrollToTopButton.js
  client/components/topNav.js
  client/data/homeStaticData.js
  client/package-lock.json
  client/package.json
  client/pages/habit/search/index.js
  client/pages/index.js
  client/pages/user/signup.js
  client/public/sw.js.map
Labels: FE, Feat, Fix

#118 feat - #99: 마이페이지 프로그레스바 제외 구현
  client/.gitignore
  client/components/header.js
  client/pages/user/mypage/index.js
  client/public/sw.js.map
Labels: FE, Feat, Design

#111 feat - #16: CustomBeanUtils 구현
  server/src/main/java/challenge/server/utils/CustomBeanUtils.java
Labels: BE, Feat

#119 fix: 런타임 에러 해결
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
Labels: BE, Fix

#120 feat: API 통신을 위한 챌린지 조회 기능 추가
  server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
  server/src/main/java/challenge/server/challenge/repository/ChallengeRepository.java
  server/src/main/java/challenge/server/challenge/service/ChallengeService.java
Labels: BE, Feat

#125 [FE] Feat - #50 myPageMenu 구현 및 button css 수정, footer 마크업 수정
  client/components/button/SignUpButton.js
  client/components/button/checkButton.js
  client/components/certificationModal.js
  client/components/footer.js
  client/components/myPageMenu.js
  client/components/wantedHabit.js
  client/public/image/66logoForModal.svg
  client/tailwind.config.js
Labels: FE, Feat, Design, Style, Rename, Remove

#127 [FE] rename: MyPageMenu, Signup button 이름 변경
  client/components/button/signUpButton.js
  client/components/myPageMenuList.js
Labels: Rename

#128 feat - #117: Slide Banner 추가 구현 완료
  client/components/header.js
  client/components/slideBanner.js
  client/package-lock.json
  client/package.json
  client/pages/user/mypage/savedHabit.js
  client/public/sw.js.map
Labels: FE, Feat

#123 fix - #17: Bookmark 조회 핸들러메서드 이동
  server/src/main/java/challenge/server/bookmark/controller/BookmarkController.java
  server/src/main/java/challenge/server/user/controller/UserController.java
Labels: BE, Fix

#131 feat - #117: Process Gauage Bar 구현
  client/pages/user/mypage/index.js
Labels: FE, Feat

#132 chore - #65: ts 새출발 시작(for refactoring)
  client/package-lock.json
  client/package.json
  client/tsconfig.json
Labels: Feat, Chore

#133 feat - #124: Image 업로드 기능 구현
  server/build.gradle
  server/src/main/java/challenge/server/ServerApplication.java
  server/src/main/java/challenge/server/auth/dto/AuthDto.java
  server/src/main/java/challenge/server/auth/entity/Auth.java
  server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
  server/src/main/java/challenge/server/exception/ExceptionCode.java
  server/src/main/java/challenge/server/file/controller/FileUploadController.java
  server/src/main/java/challenge/server/file/dto/FileDto.java
  server/src/main/java/challenge/server/file/service/FileUploadService.java
  server/src/main/java/challenge/server/file/storage/AmazonS3ResourceStorage.java
  server/src/main/java/challenge/server/file/util/MultipartUtil.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/test/java/challenge/server/config/JasyptConfigTest.java
  server/src/test/resources/application.yml
Labels: BE, Feat, Chore

#135 fix: JasypConfigTest 실패 해결
  server/src/test/java/challenge/server/config/JasyptConfigTest.java
Labels: BE, Fix

#140 refactor - #139: signup edit 타입스크립트 리팩토링
  client/module/userFunctionMoudules.js
  client/pages/user/mypage/edit.tsx
  client/pages/user/signup.tsx
Labels: FE, Refactor

#142 refactor - #141: 리덕스 관련 파일 리팩토링
  client/ducks/loginIdentitySlice.js
  client/ducks/loginIdentitySlice.ts
  client/ducks/store.ts
  client/module/cookies.js
  client/module/cookies.ts
  client/pages/user/mypage/edit.tsx
  client/pages/user/signup.tsx
Labels: FE, Refactor

#144 refactor - #65: Login, Custom Hook, 몇몇 Component Typescript Refactoring
  client/components/habitElement.tsx
  client/components/habitWrapperHorizontal.tsx
  client/components/habitWrapperVertical.tsx
  client/components/layout/layout.tsx
  client/components/topNav.tsx
  client/hooks/useIntersection.ts
  client/pages/_app.tsx
  client/pages/index.tsx
  client/pages/user/login.tsx
  client/pages/user/mypage/savedHabit.tsx
Labels: FE, Refactor

#145 refactor - #137: Habit 관련 Blocks 및 Page TS Refactoring
  client/components/authArticle.tsx
  client/components/fileUploader.tsx
  client/components/modal.tsx
  client/components/reviewArticle.tsx
  client/components/slideBanner.tsx
  client/components/topNav.tsx
  client/data/homeStaticData.ts
  client/data/navData.ts
  client/pages/_document.tsx
  client/pages/habit/detail/[habitId]/auth.tsx
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/habit/detail/[habitId]/review.tsx
  client/pages/habit/detail/[habitId]/statistic.tsx
  client/pages/habit/post.tsx
  client/pages/home/hotlist.tsx
  client/pages/home/newlist.js
  client/pages/home/newlist.tsx
  client/pages/home/recommendlist.js
  client/pages/home/recommendlist.tsx
  client/pages/index.tsx
  client/pages/user/mypage/madehabit.tsx
Labels: FE, Refactor

#149 refactor - #143: 리덕스 코드 리팩토링
  client/ducks/loginIdentitySlice.ts
  client/pages/user/login.tsx
  client/pages/user/mypage/edit.tsx
  client/pages/user/signup.tsx
Labels: FE, Refactor

#152 feat - #124: File 수정, 삭제, 썸네일 및 확장자 검증 구현
  server/src/main/java/challenge/server/auth/entity/Auth.java
  server/src/main/java/challenge/server/auth/service/AuthService.java
  server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
  server/src/main/java/challenge/server/exception/ExceptionCode.java
  server/src/main/java/challenge/server/file/config/AmazonS3Config.java
  server/src/main/java/challenge/server/file/controller/FileUploadController.java
  server/src/main/java/challenge/server/file/dto/FileDto.java
  server/src/main/java/challenge/server/file/service/FileUploadService.java
  server/src/main/java/challenge/server/file/storage/AmazonS3ResourceStorage.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/test/resources/application.yml
Labels: BE, Feat, Comment, Docs, Remove

#151 refactor - #146: Ajax Module TS Refactoring 1차 완료
  client/components/scrollToTopButton.tsx
  client/module/bookmarkFunctionMoudules.ts
  client/module/habitFunctionMoudules.ts
  client/module/moduleInterface.ts
  client/module/userFunctionMoudules.ts
Labels: FE, Refactor

#154 refactor - #150: 바텀 네비게이션 및 드롭다운 리팩토링
  client/components/authArticle.tsx
  client/components/bottomNav/bottomNav.tsx
  client/components/bottomNav/editHabitBottomNav.tsx
  client/components/bottomNav/habitPageBottomNav.js
  client/components/bottomNav/habitPageBottomNav.tsx
  client/components/bottomNav/mainBottomNav.tsx
  client/components/bottomNav/reviewHabitBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
  client/components/dropDown.tsx
  client/components/reviewArticle.tsx
Labels: FE, Feat, Refactor

#158 refactor - #138: MyPage 리팩터링 완료
  client/package-lock.json
  client/package.json
  client/pages/user/mypage/index.tsx
  client/public/sw.js.map
Labels: FE, Refactor

#160 fix - #146: Habit POST File Upload 수정 1차
  client/components/fileUploader.tsx
  client/components/loadingIndicator.tsx
  client/pages/habit/post.tsx
  client/pages/habit/search/[keyword].js
  client/tsconfig.json
Labels: FE, Fix

#162 refactor - #155 서치 페이지 타입스크립트 리팩토링 완료
  client/components/dropDown.tsx
  client/pages/_app.tsx
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/habit/search/index.tsx
  client/public/sw.js.map
Labels: FE, Refactor

#164 fix: NullPointerException 해결
  server/src/main/java/challenge/server/challenge/service/ChallengeService.java
  server/src/test/java/challenge/server/challenge/service/ChallengeServiceTest.java
  server/src/test/resources/application.yml
Labels: BE, Fix

#165 fix - #146: Habit Post File Upload 수정 완료
  client/components/fileUploader.tsx
  client/pages/habit/post.tsx
  client/public/sw.js.map
  client/tsconfig.json
Labels: Feat, Fix, Refactor

#169 feat - #159: MyPage 관련 컴포넌트 TS 전환, 통합 추후 인증 모달 손보기
  client/components/certificationModal.tsx
  client/components/header.tsx
  client/components/myPageMenuList.js
  client/components/myPageMenuList.tsx
  client/pages/user/mypage/index.tsx
Labels: FE, Feat, Refactor

#170 refactor - #155: 바텀 네비게이션 리팩토링
  client/components/bottomNav/editHabitBottomNav.tsx
  client/components/bottomNav/habitPageBottomNav.tsx
  client/components/bottomNav/reviewHabitBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
  client/components/dropDown.tsx
  client/components/modal.tsx
  client/module/habitFunctionMoudules.ts
  client/module/userFunctionMoudules.ts
  client/pages/auth/index.tsx
  client/pages/user/signup.tsx
Labels: FE, Refactor

#178 feat - #177: 모듈 수정
  client/module/bookmarkFunctionMoudules.ts
  client/module/challengeFunctionMoudules.js
  client/module/habitFunctionMoudules.ts
  client/module/moduleInterface.ts
  client/module/userFunctionMoudules.ts
  client/public/sw.js.map
Labels: FE, Feat

#182 feat - #179: 서치 페이지 데이터 연결 및 커스텀 훅 url 부분 수정
  client/hooks/useIntersection.ts
  client/pages/habit/search/index.tsx
Labels: FE, Feat

#184 feat - #166: Date Format Module 구현 및 Habit 관련 Comp Ajax 연결 작업 1차
  client/.env
  client/components/authArticle.tsx
  client/components/button/checkButton.js
  client/components/button/signUpButton.js
  client/components/habitElement.tsx
  client/components/habitWrapperHorizontal.tsx
  client/components/habitWrapperVertical.tsx
  client/data/homeStaticData.ts
  client/hooks/useIntersection.ts
  client/module/authFunctionMoudules.js
  client/module/authFunctionMoudules.ts
  client/module/dateFormat.ts
  client/module/kakaoShare.tsx
  client/package-lock.json
  client/package.json
  client/pages/habit/detail/[habitId]/auth.tsx
  client/pages/habit/detail/[habitId]/review.tsx
  client/pages/user/login.tsx
Labels: FE, Feat, Fix

#186 feat - #12: OAuth2 로그인 구현(Google, Naver, Kakao)
  .gitignore
  server/build.gradle
  server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepositoryImpl.java
  server/src/main/java/challenge/server/config/SecurityConfig.java
  server/src/main/java/challenge/server/security/dto/LoginDto.java
  server/src/main/java/challenge/server/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/challenge/server/security/oauth/dto/OAuthAttributes.java
  server/src/main/java/challenge/server/security/oauth/dto/SessionUser.java
  server/src/main/java/challenge/server/security/oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/challenge/server/security/oauth/service/CustomOAuth2UserService.java
  server/src/main/java/challenge/server/user/entity/User.java
  server/src/main/resources/application-server.yml
Labels: BE, Feat, Docs, Chore

#189 feat: OAuth2 redirect-uri 수정
  server/src/main/java/challenge/server/security/oauth/dto/SessionUser.java
  server/src/main/java/challenge/server/security/oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/resources/application-server.yml
Labels: BE, Feat

#190 feat: redirect-uri 수정
  server/src/main/resources/application-server.yml
Labels: BE, Feat

#194 feat - #183: firebase service worker 프로토타입 등록
  client/.env
  client/components/bottomNav/habitPageBottomNav.tsx
  client/components/bottomNav/reviewHabitBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
  client/data/navData.ts
  client/module/habitFunctionMoudules.ts
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/user/mypage/index.tsx
  client/public/firebase-messaging-sw.js
  client/util/firebase.ts
Labels: FE, Feat

#193 fix - #166: Habit 관련 Comp & Page Ajax 연결 관련 코드 수정
  client/components/authArticle.tsx
  client/components/dropDown.tsx
  client/components/footer.tsx
  client/components/modal.tsx
  client/components/reviewArticle.tsx
  client/data/reportData.ts
  client/hooks/useIntersection.ts
  client/module/authFunctionMoudules.ts
  client/module/habitFunctionMoudules.ts
  client/module/moduleInterface.ts
  client/module/reportFunctionMoudules.js
  client/module/reportFunctionMoudules.ts
  client/module/reviewFunctionModules.js
  client/module/reviewFunctionModules.ts
  client/pages/habit/detail/[habitId]/auth.tsx
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/habit/detail/[habitId]/review.tsx
  client/pages/home/hotlist.tsx
  client/pages/home/newlist.tsx
  client/pages/home/recommendlist.tsx
Labels: FE, Fix

#197 feat - #180: 마이페이지 모듈 연결, 로그아웃 구현, 리다이렉트 구현
  client/components/certificationModal.tsx
  client/components/modal.tsx
  client/components/myPageMenuList.tsx
  client/module/cookies.ts
  client/module/moduleInterface.ts
  client/module/userFunctionMoudules.ts
  client/pages/auth/index.tsx
  client/pages/user/mypage/index.tsx
  client/pages/user/mypage/madehabit.tsx
  client/pages/user/mypage/savedhabit.tsx
  client/pages/user/mypage/withdraw.tsx
Labels: FE, Feat

#199 fix - #196: Header 라우팅 관련부분 수정완료
  client/components/header.tsx
Labels: FE, Fix

#201 fix - #30: Habit Patch userId 파라미터 삭제, DTO username 필드 추가
  server/src/main/java/challenge/server/auth/dto/AuthDto.java
  server/src/main/java/challenge/server/auth/mapper/AuthMapper.java
  server/src/main/java/challenge/server/habit/controller/HabitController.java
  server/src/main/java/challenge/server/habit/dto/HabitDto.java
  server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
  server/src/main/java/challenge/server/review/dto/ReviewDto.java
  server/src/main/java/challenge/server/review/mapper/ReviewMapper.java
Labels: BE, Feat, Fix

#203 feat - #202: 찜한 습관, 내가 만든 습관 기능 구현, Header 콘솔 삭제
  client/components/header.tsx
  client/pages/auth/index.tsx
  client/pages/user/mypage/madehabit.tsx
  client/pages/user/mypage/savedhabit.tsx
Labels: FE, Feat, Fix

#204 feat - #195: 하단 네비게이션 데이터 상태에 따른 분기 및 인증 페이지 데이터 전송 구현
  client/.env
  client/components/bottomNav/editHabitBottomNav.tsx
  client/components/bottomNav/habitPageBottomNav.tsx
  client/components/bottomNav/reviewHabitBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
  client/components/modal.tsx
  client/module/authFunctionMoudules.ts
  client/module/challengeFunctionMoudules.ts
  client/module/reviewFunctionModules.ts
  client/pages/auth/index.tsx
  client/pages/habit/search/index.tsx
Labels: FE, Feat

#206 fix - #166: Habit 관련 AJax 연결 및 일부 코드 수정
  client/components/authArticle.tsx
  client/components/dropDown.tsx
  client/components/modal.tsx
  client/components/reviewArticle.tsx
  client/components/topNav.tsx
  client/data/navData.ts
  client/hooks/useIntersection.ts
  client/module/authFunctionMoudules.ts
  client/module/habitFunctionMoudules.ts
  client/module/moduleInterface.ts
  client/module/reportFunctionMoudules.ts
  client/next.config.js
  client/pages/habit/detail/[habitId]/auth.tsx
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/habit/detail/[habitId]/review.tsx
  client/pages/habit/post.tsx
  client/pages/user/login.tsx
Labels: FE, Feat, Fix, Refactor

#215 feat - #12: OAuth2 프론트엔드로 넘기는 redirect url 변경
  server/src/main/java/challenge/server/security/oauth/handler/OAuth2MemberSuccessHandler.java
Labels: BE, Feat

#217 feat - #iss207: 하단 네비게이션 css 조절 및 sns 카카오 공유(모바일x)구현
  client/.env
  client/components/bottomNav/editHabitBottomNav.tsx
  client/components/bottomNav/mainBottomNav.tsx
  client/components/bottomNav/reviewHabitBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
  client/components/dropDown.tsx
  client/components/modal.tsx
  client/data/homeStaticData.ts
  client/module/kakaoShare.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/index.tsx
  client/public/firebase-messaging-sw.js
  client/util/firebase.ts
Labels: FE, Feat, Design

#213 Design: certificationModal css 작업
  client/components/certificationModal.tsx
  client/public/image/prizeborder.jpg
Labels: FE, Design, Style

#219 feat - #218: habitElement 북마크 호스트는 안보이도록 수정
  client/components/habitElement.tsx
  client/components/habitWrapperVertical.tsx
  client/pages/habit/search/index.tsx
Labels: FE, Feat

#221 feat - #205: 마이페이지 통신 변수명 수정, 프로필 사진 변경기능, Header 아이콘 크기 수정 및 공유하기 삭제, 마이페이지 인증서 발급 수정
  client/components/header.tsx
  client/components/myPageMenuList.tsx
  client/module/moduleInterface.ts
  client/module/userFunctionMoudules.ts
  client/pages/user/mypage/index.tsx
Labels: FE

#223 design - #218: 검색 페이지 카테고리 grid 변경 upscroll 위치 변경
  client/components/habitWrapperVertical.tsx
  client/components/scrollToTopButton.tsx
  client/pages/habit/search/index.tsx
Labels: FE, Design

#233 fix - #32: 컴파일 오류 해결
  server/src/main/java/challenge/server/user/service/UserService.java
Labels: BE, Fix

#238 fix: 더미데이터 img 칼럼 http 수정
  server/src/main/resources/db/h2/data.sql
Labels: BE, Fix

#237 feat - #236: 인증서 발급 UI 변경, Header에 홈버튼 추가
  client/components/header.tsx
  client/components/myPageMenuList.tsx
  client/pages/user/mypage/index.tsx
  client/pages/user/mypage/withdraw.tsx
Labels: FE, Feat, Design

#239 fix: NullPointerException 해결
  server/src/main/java/challenge/server/challenge/entity/Challenge.java
Labels: BE, Fix

#240 fix - #32: 회원 가입 전 이메일 인증 기능 주석 처리
  server/src/main/java/challenge/server/user/service/UserService.java
Labels: BE, Fix

#241 feat: 습관 정렬(추천순) 기능 추가
  server/src/main/java/challenge/server/habit/controller/HabitController.java
  server/src/main/java/challenge/server/habit/entity/Habit.java
  server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
  server/src/main/java/challenge/server/habit/repository/HabitCustomRepositoryImpl.java
  server/src/main/java/challenge/server/habit/service/HabitService.java
  server/src/main/resources/db/h2/data.sql
Labels: BE, Feat

#243 fix: MaxUploadSizeExceededException 해결
  server/src/main/resources/application-server.yml
Labels: BE, Fix

#244 fix - #148: 일부 오류 수정
  client/components/fileUploader.tsx
  client/components/habitElement.tsx
  client/next.config.js
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/habit/post.tsx
  client/pages/habit/search/index.tsx
  client/pages/user/login.tsx
Labels: FE, Fix

#245 feat - #218: 전체적인 에러 잡기
  client/components/bottomNav/editHabitBottomNav.tsx
  client/components/bottomNav/habitPageBottomNav.tsx
  client/components/bottomNav/mainBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
  client/module/challengeFunctionMoudules.ts
  client/pages/auth/index.tsx
Labels: FE, Fix

#248 design - #148: Modal 및 페이지 전체 CSS 수정
  client/components/habitElement.tsx
  client/components/header.tsx
  client/components/modal.tsx
  client/components/topNav.tsx
  client/data/homeStaticData.ts
  client/ducks/loginIdentitySlice.ts
  client/pages/habit/search/index.tsx
Labels: FE, Design

#251 chore - #250: 빌드를 위한 package.json 수정
  client/package.json
Labels: FE, Chore

#255 Iss249
  server/src/main/resources/application-server.yml
Labels: BE, Docs

#256 docs: datasource url 수정
  server/src/main/resources/application-server.yml
Labels: BE, Docs

#257 docs: datasource url 수정
  server/src/main/resources/application-server.yml
Labels: BE, Docs

#262 chore - #250: package 수정(export 삭제)
  client/package.json
Labels: FE, Chore

#271 feat - #246: 서버 주소 수정
  client/.env
  client/module/kakaoShare.tsx
  client/package-lock.json
Labels: FE, Feat

#276 feat - #148: Infinite Scroll Login Change
  client/hooks/useIntersection.ts
  client/pages/habit/detail/[habitId]/auth.tsx
  client/pages/habit/detail/[habitId]/review.tsx
  client/pages/home/hotlist.tsx
  client/pages/home/newlist.tsx
  client/pages/home/recommendlist.tsx
  client/pages/user/login.tsx
  client/styles/globals.css
Labels: FE, Feat

#279 fix - #148: Search Page 오류 수정
  client/pages/habit/search/index.tsx
Labels: FE, Fix

#282 feat: 인증서 모달 props 내려주기
  client/components/certificationModal.tsx
  client/components/myPageMenuList.tsx
  client/module/userFunctionMoudules.ts
  client/pages/habit/search/index.tsx
  client/pages/user/mypage/index.tsx
Labels: FE, Feat

#284 feat - #283: 카카오 쉐어 주소 수정 및 파이어베이스 토큰 발급 컴포넌트 제작
  client/components/header.tsx
  client/components/pushSubscribe.tsx
  client/ducks/loginIdentitySlice.ts
  client/module/kakaoShare.tsx
  client/pages/_app.tsx
Labels: FE, Feat

#280 feat - #30: Report Entity, Habit DTO 및 Mapper 수정
  server/src/main/java/challenge/server/habit/dto/HabitDto.java
  server/src/main/java/challenge/server/habit/entity/Habit.java
  server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
  server/src/main/java/challenge/server/report/dto/ReportDto.java
  server/src/main/java/challenge/server/report/entity/Report.java
Labels: BE, Feat

#288 feat - #283: http 통신 관련 수정
  client/pages/_document.tsx
Labels: FE, Feat

#287 feat - #191: no-offset pagination 구현
  server/src/main/java/challenge/server/auth/repository/AuthCustomRepository.java
  server/src/main/java/challenge/server/auth/repository/AuthCustomRepositoryImpl.java
  server/src/main/java/challenge/server/auth/service/AuthService.java
  server/src/main/java/challenge/server/bookmark/repository/BookmarkCustomRepository.java
  server/src/main/java/challenge/server/bookmark/repository/BookmarkCustomRepositoryImpl.java
  server/src/main/java/challenge/server/bookmark/service/BookmarkService.java
  server/src/main/java/challenge/server/challenge/controller/ChallengeController.java
  server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepository.java
  server/src/main/java/challenge/server/challenge/repository/ChallengeCustomRepositoryImpl.java
  server/src/main/java/challenge/server/challenge/repository/ChallengeRepository.java
  server/src/main/java/challenge/server/challenge/service/ChallengeService.java
  server/src/main/java/challenge/server/habit/controller/HabitController.java
  server/src/main/java/challenge/server/habit/repository/HabitCustomRepository.java
  server/src/main/java/challenge/server/habit/repository/HabitCustomRepositoryImpl.java
  server/src/main/java/challenge/server/habit/repository/HabitRepository.java
  server/src/main/java/challenge/server/habit/service/HabitService.java
  server/src/main/java/challenge/server/report/repository/ReportCustomRepository.java
  server/src/main/java/challenge/server/report/repository/ReportCustomRepositoryImpl.java
  server/src/main/java/challenge/server/report/repository/ReportRepository.java
  server/src/main/java/challenge/server/report/service/ReportService.java
  server/src/main/java/challenge/server/review/repository/ReviewCustomRepository.java
  server/src/main/java/challenge/server/review/repository/ReviewCustomRepositoryImpl.java
  server/src/main/java/challenge/server/review/service/ReviewService.java
  server/src/main/java/challenge/server/user/controller/UserController.java
  server/src/main/java/challenge/server/user/service/UserService.java
Labels: BE, Feat

#289 feat - #283: http 통신 관련 수정
  client/pages/_document.tsx
Labels: FE, Feat

#294 feat - #148: Habit Edit 구현 및 React-Quill 도입
  client/components/slideBanner.tsx
  client/data/bookStaticData.ts
  client/data/categoryData.ts
  client/data/homeStaticData.ts
  client/hooks/useIntersection.ts
  client/module/habitFunctionMoudules.ts
  client/module/moduleInterface.ts
  client/module/reactQuill.ts
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/contents/book.tsx
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/habit/edit/[habitId].tsx
  client/pages/habit/post.tsx
  client/pages/habit/search/index.tsx
  client/pages/home/hotlist.tsx
  client/pages/home/recommendlist.tsx
  client/pages/index.tsx
  client/pages/oauth.tsx
  client/public/image/defaultImg.jpg
Labels: FE, Feat, Fix, Design

#290 fix: offset pageable 오류 수정
  server/src/main/java/challenge/server/habit/controller/HabitController.java
  server/src/main/java/challenge/server/habit/dto/HabitDto.java
  server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
  server/src/main/java/challenge/server/habit/statistics/AgeRatio.java
  server/src/main/java/challenge/server/habit/statistics/SexRatio.java
  server/src/main/java/challenge/server/habit/statistics/StatusRatio.java
  server/src/main/resources/application-server.yml
Labels: BE, Fix

#295 Iss
  server/src/main/java/challenge/server/auth/repository/AuthCustomRepositoryImpl.java
  server/src/main/java/challenge/server/habit/repository/HabitCustomRepository.java
  server/src/main/java/challenge/server/habit/repository/HabitCustomRepositoryImpl.java
  server/src/main/java/challenge/server/habit/service/HabitService.java
  server/src/main/java/challenge/server/user/entity/User.java
Labels: BE, Fix

#297 fix: QClass Compile 에러 해결
  server/src/main/java/challenge/server/security/user/repository/EmailVerificationCustomRepositoryImpl.java
Labels: BE, Fix

#301 feat - #300: 회원가입 페이지 인증 알림 메시지 크기 조절
  client/.env
  client/pages/user/signup.tsx
Labels: FE, Feat

#299 fix - #30: bodyHTML 필드명 수정, fail 이미지 optional 적용
  server/src/main/java/challenge/server/habit/controller/HabitController.java
  server/src/main/java/challenge/server/habit/dto/HabitDto.java
  server/src/main/java/challenge/server/habit/entity/Habit.java
  server/src/main/java/challenge/server/habit/mapper/HabitMapperImpl.java
Labels: BE

#304 design - #230: Bottom Nav 및 SignUp 일부 UI 수정
  client/components/bottomNav/bottomNav.tsx
  client/pages/user/signup.tsx
Labels: FE, Design

#303 fix - #12: OAuth2 로그인 Uri 업데이트
  server/src/main/java/challenge/server/security/oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/challenge/server/security/user/dto/UserDto.java
  server/src/main/java/challenge/server/security/user/service/UserService.java
Labels: BE, Fix

#305 feat - #300 로그인 부분 상태코드에 따른 분기 설정
  client/pages/user/login.tsx
  client/pages/user/signup.tsx
Labels: FE, Feat

#306 docs - #300: 환경 변수 파일 삭제
  client/.env
  client/pages/user/signup.tsx
Labels: FE, Docs

#307 feat: OAuth 페이지 헤더 숨기기, 회원가입시 나이-성별 추가, OAuth 나이-성별 입력페이지 추가, 회원탈퇴 수정
  client/components/header.tsx
  client/pages/user/mypage/withdraw.tsx
  client/pages/user/oauthsignup.tsx
  client/pages/user/signup.tsx
Labels: FE, Feat, Design

#285 feat - #275: certificationModal 데이터바인딩
  client/components/certificationModal.tsx
  client/components/myPageMenuList.tsx
Labels: FE, Feat

#309 feat - #230: Access Token 로직 변경
  client/ducks/loginIdentitySlice.ts
  client/module/authFunctionMoudules.ts
  client/module/bookmarkFunctionMoudules.ts
  client/module/challengeFunctionMoudules.ts
  client/module/habitFunctionMoudules.ts
  client/module/jsonWebToken.ts
  client/module/reportFunctionMoudules.ts
  client/module/reviewFunctionModules.ts
  client/module/userFunctionMoudules.ts
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/oauth.tsx
Labels: FE, Feat

#310 feat - #230: Access Token 로직 변경2
  client/module/jsonWebToken.ts
Labels: FE, Feat

#312 fix: compileQuerydsl 에러 해결
  server/src/main/java/challenge/server/user/repository/EmailVerificationCustomRepositoryImpl.java
Labels: BE, Fix

#313 feat - #300: 푸터 수정 및 userintersection null 값 수정
  client/components/footer.tsx
  client/hooks/useIntersection.ts
  client/pages/index.tsx
Labels: FE, Feat, Design

#318 feat - #230: Refresh Token으로 Access Token reissue 구현
  client/components/slideBanner.tsx
  client/ducks/loginIdentitySlice.ts
  client/module/jsonWebToken.ts
  client/pages/_app.tsx
  client/pages/habit/post.tsx
  client/pages/oauth.tsx
Labels: FE, Feat

#317 [FE] Design: mypagemenulist, certificationModal css
  client/components/certificationModal.tsx
  client/components/myPageMenuList.tsx
Labels: FE, Design, Style

#320 feat - #308: 마이페이지 css 손보기
  client/components/myPageMenuList.tsx
  client/pages/user/mypage/index.tsx
Labels: FE, Feat, Design

#321 fix - #230: 비로그인 시 발생하는 에러 수정
  client/module/jsonWebToken.ts
Labels: FE, Fix

#330 feat - #231: Book Page 구현
  client/components/header.tsx
  client/data/bookStaticData.ts
Labels: FE, Feat

#327 feat - #300: 상세페이지 통계 탭 구현 중 패스
  client/components/dropDown.tsx
  client/hooks/useIntersection.ts
  client/module/habitFunctionMoudules.ts
  client/pages/habit/detail/[habitId]/statistic.tsx
Labels: FE, Feat

#331 feat - #322: 각종 CSS 수정
  client/components/myPageMenuList.tsx
  client/package-lock.json
  client/package.json
  client/pages/user/mypage/index.tsx
  client/pages/user/mypage/madehabit.tsx
  client/pages/user/mypage/savedhabit.tsx
  client/pages/user/oauthsignup.tsx
  client/pages/user/signup.tsx
Labels: FE, Feat

#329 Design - #328: certificationModal css, 테일윈드 콘픽 추가
  client/components/certificationModal.tsx
  client/tailwind.config.js
Labels: FE, Design

#333 fix - #231: Habit POST 오류 수정
  client/pages/habit/post.tsx
Labels: FE, Fix

#334 fix - #231: Habit Post & Detail 에러 수정
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/habit/post.tsx
Labels: FE, Fix

#339 feat - #338: 세로스크롤 막히는 거 해결
  client/components/bottomNav/bottomNav.tsx
Labels: FE, Feat

#342 design - #341: 버튼 이름 바꾸기
  client/components/bottomNav/editHabitBottomNav.tsx
  client/components/bottomNav/mainBottomNav.tsx
  client/components/bottomNav/reviewHabitBottomNav.tsx
  client/components/bottomNav/startHabitBottomNav.tsx
  client/components/header.tsx
  client/pages/user/login.tsx
  client/pages/user/signup.tsx
Labels: FE, Design

#344 design - #231: Habit Detail UI 수정
  client/hooks/useIntersection.ts
  client/pages/habit/detail/[habitId]/index.tsx
  client/pages/home/newlist.tsx
Labels: FE, Design

#349 chore - #348: pm2 멀티 스레딩 도전
  client/pages/user/mypage/index.tsx
Labels: FE, Chore

#350 feat - #345: 푸시 알림 구현 중
  client/components/bottomNav/mainBottomNav.tsx
  client/pages/api/webpush.ts
  client/public/firebase-messaging-sw.js
  client/util/firebase.ts
Labels: FE, Feat

#351 fix: timeout 에러 해결
  server/src/main/java/challenge/server/file/storage/AmazonS3ResourceStorage.java
Labels: BE, Fix
